# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog Why R - ogólnopolskiej konferencji użytkowników R
email: whyr@mini.pw.edu.pl
description: > # this means to ignore newlines until "baseurl:"
  Liczymy na wiele nowych wiadomości z metodologii badań i informacji z dziedziny rozwoju oprogramowania. Zapewniamy świetny program społecznościowy
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://whyr.pl" # the base hostname & protocol for your site
twitter_username: whyRconf
github_username:  whyR-conference
# facebook_username: wwhyRconf

encoding: utf-8

# Build settings
markdown: kramdown
